### ISSUE TITLE
Have better conditions

### ISSUE THREAD

**Issue by janiskemper** [hivelocity/cluster-api-provider-hivelocity#103]
/kind proposal

***Goals***
Improve conditions to improve the usability of the operator. 

**Detailed Description**

We should improve the conditions in CAPHV. There are the following tasks to do:

## Tasks
- [ ] Change rate limit condition to the same as in CAPH
- [ ] Add condition that no available device has been found
- [ ] printcolumns with message and reason like in CAPH
- [ ] conditions Summary like in CAPH
- [ ] Add condition for SSH key not found
- [ ] Add condition for server off
- [ ] Add conditions for TargetClusterReadyCondition
- [ ] Add condition for wrong API token

**Comment by aniruddha2000** [comment]
> Add condition that no available device has been found

isn't it the reason for it https://github.com/hivelocity/cluster-api-provider-hivelocity/blob/37f0a5563e72b3e717ad23a987db08f03af6671b/api/v1alpha1/conditions_const.go#L25 ?

**Comment by aniruddha2000** [comment]
> Add condition for server off

do you mean by this?
https://github.com/hivelocity/cluster-api-provider-hivelocity/blob/fc8e3899b87a7246b6fbeeeabf634af96bbc54bc/pkg/services/hivelocity/client/hvclient.go#L47

**Comment by aniruddha2000** [comment]
> Add conditions for TargetClusterReadyCondition

I see a https://github.com/hivelocity/cluster-api-provider-hivelocity/blob/fc8e3899b87a7246b6fbeeeabf634af96bbc54bc/api/v1alpha1/conditions_const.go#L40 is that same we are talking about?
